/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ReservationRequest,
  ReservationResponse
} from '../../models';

import { customInstance } from '../../mutator';




export type getReservationsResponse200 = {
  data: ReservationResponse[]
  status: 200
}
    
export type getReservationsResponseSuccess = (getReservationsResponse200) & {
  headers: Headers;
};
;

export type getReservationsResponse = (getReservationsResponseSuccess)

export const getGetReservationsUrl = () => {


  

  return `/reservations`
}

export const getReservations = async ( options?: RequestInit): Promise<getReservationsResponse> => {
  
  return customInstance<getReservationsResponse>(getGetReservationsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetReservationsQueryKey = () => {
    return [
    `/reservations`
    ] as const;
    }

    
export const getGetReservationsQueryOptions = <TData = Awaited<ReturnType<typeof getReservations>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReservationsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReservations>>> = ({ signal }) => getReservations({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReservationsQueryResult = NonNullable<Awaited<ReturnType<typeof getReservations>>>
export type GetReservationsQueryError = unknown


export function useGetReservations<TData = Awaited<ReturnType<typeof getReservations>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservations>>,
          TError,
          Awaited<ReturnType<typeof getReservations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReservations<TData = Awaited<ReturnType<typeof getReservations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReservations>>,
          TError,
          Awaited<ReturnType<typeof getReservations>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReservations<TData = Awaited<ReturnType<typeof getReservations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetReservations<TData = Awaited<ReturnType<typeof getReservations>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReservations>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReservationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type createReservationResponse200 = {
  data: ReservationResponse
  status: 200
}
    
export type createReservationResponseSuccess = (createReservationResponse200) & {
  headers: Headers;
};
;

export type createReservationResponse = (createReservationResponseSuccess)

export const getCreateReservationUrl = () => {


  

  return `/reservations`
}

export const createReservation = async (reservationRequest: ReservationRequest, options?: RequestInit): Promise<createReservationResponse> => {
  
  return customInstance<createReservationResponse>(getCreateReservationUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      reservationRequest,)
  }
);}




export const getCreateReservationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationRequest}, TContext> => {

const mutationKey = ['createReservation'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createReservation>>, {data: ReservationRequest}> = (props) => {
          const {data} = props ?? {};

          return  createReservation(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateReservationMutationResult = NonNullable<Awaited<ReturnType<typeof createReservation>>>
    export type CreateReservationMutationBody = ReservationRequest
    export type CreateReservationMutationError = unknown

    export const useCreateReservation = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createReservation>>, TError,{data: ReservationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createReservation>>,
        TError,
        {data: ReservationRequest},
        TContext
      > => {
      return useMutation(getCreateReservationMutationOptions(options), queryClient);
    }
    