/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  MovieBrowseResponse,
  MovieCreateShowResponse,
  MovieCreationRequest,
  MovieCreationResponse
} from '../../models';

import { customInstance } from '../../mutator';




/**
 * Create a new movie show with the provided information
 * @summary Create a movie show
 */
export type createMovieResponse201 = {
  data: MovieCreationResponse
  status: 201
}

export type createMovieResponse400 = {
  data: MovieCreationResponse
  status: 400
}
    
export type createMovieResponseSuccess = (createMovieResponse201) & {
  headers: Headers;
};
export type createMovieResponseError = (createMovieResponse400) & {
  headers: Headers;
};

export type createMovieResponse = (createMovieResponseSuccess | createMovieResponseError)

export const getCreateMovieUrl = () => {


  

  return `/movie/createShow`
}

export const createMovie = async (movieCreationRequest: MovieCreationRequest, options?: RequestInit): Promise<createMovieResponse> => {
  
  return customInstance<createMovieResponse>(getCreateMovieUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      movieCreationRequest,)
  }
);}




export const getCreateMovieMutationOptions = <TError = MovieCreationResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMovie>>, TError,{data: MovieCreationRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createMovie>>, TError,{data: MovieCreationRequest}, TContext> => {

const mutationKey = ['createMovie'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createMovie>>, {data: MovieCreationRequest}> = (props) => {
          const {data} = props ?? {};

          return  createMovie(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateMovieMutationResult = NonNullable<Awaited<ReturnType<typeof createMovie>>>
    export type CreateMovieMutationBody = MovieCreationRequest
    export type CreateMovieMutationError = MovieCreationResponse

    /**
 * @summary Create a movie show
 */
export const useCreateMovie = <TError = MovieCreationResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createMovie>>, TError,{data: MovieCreationRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createMovie>>,
        TError,
        {data: MovieCreationRequest},
        TContext
      > => {
      return useMutation(getCreateMovieMutationOptions(options), queryClient);
    }
    /**
 * Retrieve a specific movie by its ID
 * @summary Get movie by ID
 */
export type getMovieByIdResponse200 = {
  data: MovieCreateShowResponse
  status: 200
}

export type getMovieByIdResponse404 = {
  data: MovieCreateShowResponse
  status: 404
}
    
export type getMovieByIdResponseSuccess = (getMovieByIdResponse200) & {
  headers: Headers;
};
export type getMovieByIdResponseError = (getMovieByIdResponse404) & {
  headers: Headers;
};

export type getMovieByIdResponse = (getMovieByIdResponseSuccess | getMovieByIdResponseError)

export const getGetMovieByIdUrl = (id: string,) => {


  

  return `/movie/${id}`
}

export const getMovieById = async (id: string, options?: RequestInit): Promise<getMovieByIdResponse> => {
  
  return customInstance<getMovieByIdResponse>(getGetMovieByIdUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetMovieByIdQueryKey = (id: string,) => {
    return [
    `/movie/${id}`
    ] as const;
    }

    
export const getGetMovieByIdQueryOptions = <TData = Awaited<ReturnType<typeof getMovieById>>, TError = MovieCreateShowResponse>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMovieByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMovieById>>> = ({ signal }) => getMovieById(id, { signal });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMovieByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMovieById>>>
export type GetMovieByIdQueryError = MovieCreateShowResponse


export function useGetMovieById<TData = Awaited<ReturnType<typeof getMovieById>>, TError = MovieCreateShowResponse>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMovieById>>,
          TError,
          Awaited<ReturnType<typeof getMovieById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMovieById<TData = Awaited<ReturnType<typeof getMovieById>>, TError = MovieCreateShowResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMovieById>>,
          TError,
          Awaited<ReturnType<typeof getMovieById>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMovieById<TData = Awaited<ReturnType<typeof getMovieById>>, TError = MovieCreateShowResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get movie by ID
 */

export function useGetMovieById<TData = Awaited<ReturnType<typeof getMovieById>>, TError = MovieCreateShowResponse>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMovieById>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMovieByIdQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Delete a movie by its ID
 * @summary Delete movie
 */
export type deleteMovieResponse204 = {
  data: void
  status: 204
}

export type deleteMovieResponse404 = {
  data: void
  status: 404
}
    
export type deleteMovieResponseSuccess = (deleteMovieResponse204) & {
  headers: Headers;
};
export type deleteMovieResponseError = (deleteMovieResponse404) & {
  headers: Headers;
};

export type deleteMovieResponse = (deleteMovieResponseSuccess | deleteMovieResponseError)

export const getDeleteMovieUrl = (id: string,) => {


  

  return `/movie/${id}`
}

export const deleteMovie = async (id: string, options?: RequestInit): Promise<deleteMovieResponse> => {
  
  return customInstance<deleteMovieResponse>(getDeleteMovieUrl(id),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}




export const getDeleteMovieMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMovie>>, TError,{id: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteMovie>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteMovie'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMovie>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteMovie(id,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteMovieMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMovie>>>
    
    export type DeleteMovieMutationError = void

    /**
 * @summary Delete movie
 */
export const useDeleteMovie = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMovie>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMovie>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getDeleteMovieMutationOptions(options), queryClient);
    }
    /**
 * Retrieve movie information needed for creating a show
 * @summary Get movie information for show creation
 */
export type getAllMovieInformationsForShowCreationResponse200 = {
  data: MovieCreateShowResponse[]
  status: 200
}
    
export type getAllMovieInformationsForShowCreationResponseSuccess = (getAllMovieInformationsForShowCreationResponse200) & {
  headers: Headers;
};
;

export type getAllMovieInformationsForShowCreationResponse = (getAllMovieInformationsForShowCreationResponseSuccess)

export const getGetAllMovieInformationsForShowCreationUrl = () => {


  

  return `/movie/createShowInformation`
}

export const getAllMovieInformationsForShowCreation = async ( options?: RequestInit): Promise<getAllMovieInformationsForShowCreationResponse> => {
  
  return customInstance<getAllMovieInformationsForShowCreationResponse>(getGetAllMovieInformationsForShowCreationUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllMovieInformationsForShowCreationQueryKey = () => {
    return [
    `/movie/createShowInformation`
    ] as const;
    }

    
export const getGetAllMovieInformationsForShowCreationQueryOptions = <TData = Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllMovieInformationsForShowCreationQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>> = ({ signal }) => getAllMovieInformationsForShowCreation({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllMovieInformationsForShowCreationQueryResult = NonNullable<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>>
export type GetAllMovieInformationsForShowCreationQueryError = unknown


export function useGetAllMovieInformationsForShowCreation<TData = Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>,
          TError,
          Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMovieInformationsForShowCreation<TData = Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>,
          TError,
          Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMovieInformationsForShowCreation<TData = Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get movie information for show creation
 */

export function useGetAllMovieInformationsForShowCreation<TData = Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovieInformationsForShowCreation>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllMovieInformationsForShowCreationQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retrieve all available movies for browsing
 * @summary Get all movies
 */
export type getAllMoviesResponse200 = {
  data: MovieBrowseResponse[]
  status: 200
}
    
export type getAllMoviesResponseSuccess = (getAllMoviesResponse200) & {
  headers: Headers;
};
;

export type getAllMoviesResponse = (getAllMoviesResponseSuccess)

export const getGetAllMoviesUrl = () => {


  

  return `/movie/browse`
}

export const getAllMovies = async ( options?: RequestInit): Promise<getAllMoviesResponse> => {
  
  return customInstance<getAllMoviesResponse>(getGetAllMoviesUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetAllMoviesQueryKey = () => {
    return [
    `/movie/browse`
    ] as const;
    }

    
export const getGetAllMoviesQueryOptions = <TData = Awaited<ReturnType<typeof getAllMovies>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllMoviesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllMovies>>> = ({ signal }) => getAllMovies({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllMoviesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllMovies>>>
export type GetAllMoviesQueryError = unknown


export function useGetAllMovies<TData = Awaited<ReturnType<typeof getAllMovies>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMovies>>,
          TError,
          Awaited<ReturnType<typeof getAllMovies>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMovies<TData = Awaited<ReturnType<typeof getAllMovies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAllMovies>>,
          TError,
          Awaited<ReturnType<typeof getAllMovies>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAllMovies<TData = Awaited<ReturnType<typeof getAllMovies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get all movies
 */

export function useGetAllMovies<TData = Awaited<ReturnType<typeof getAllMovies>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAllMovies>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllMoviesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




