/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */

export interface MovieCreationRequest {
  title: string;
  description: string;
  durationMinutes: number;
  director: string;
  genre: string;
  releaseYear: number;
  imageProfile: string;
  imageLandscape: string;
}
