/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import type { Movie } from './movie';
import type { ShowSchedule } from './showSchedule';

export interface ProgramResponse {
  movie: Movie;
  shows: ShowSchedule[];
}
