/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */

export interface ReservationRequest {
  userId: string;
  theaterId: string;
  seatNumber: number;
  movieId: string;
  date: string;
}
