/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */

export interface UserLoginResponse {
  id?: string;
  providerId: string;
  name: string;
  email: string;
  avatar: string;
  role: string;
}
