/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ProgramResponse
} from '../../models';

import { customInstance } from '../../mutator';




/**
 * Retrieve tomorrow's program schedule
 * @summary Get tomorrow's program
 */
export type getTomorrowProgramResponse200 = {
  data: ProgramResponse[]
  status: 200
}
    
export type getTomorrowProgramResponseSuccess = (getTomorrowProgramResponse200) & {
  headers: Headers;
};
;

export type getTomorrowProgramResponse = (getTomorrowProgramResponseSuccess)

export const getGetTomorrowProgramUrl = () => {


  

  return `/program/tomorrow`
}

export const getTomorrowProgram = async ( options?: RequestInit): Promise<getTomorrowProgramResponse> => {
  
  return customInstance<getTomorrowProgramResponse>(getGetTomorrowProgramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTomorrowProgramQueryKey = () => {
    return [
    `/program/tomorrow`
    ] as const;
    }

    
export const getGetTomorrowProgramQueryOptions = <TData = Awaited<ReturnType<typeof getTomorrowProgram>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTomorrowProgramQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTomorrowProgram>>> = ({ signal }) => getTomorrowProgram({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTomorrowProgramQueryResult = NonNullable<Awaited<ReturnType<typeof getTomorrowProgram>>>
export type GetTomorrowProgramQueryError = unknown


export function useGetTomorrowProgram<TData = Awaited<ReturnType<typeof getTomorrowProgram>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTomorrowProgram>>,
          TError,
          Awaited<ReturnType<typeof getTomorrowProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTomorrowProgram<TData = Awaited<ReturnType<typeof getTomorrowProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTomorrowProgram>>,
          TError,
          Awaited<ReturnType<typeof getTomorrowProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTomorrowProgram<TData = Awaited<ReturnType<typeof getTomorrowProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get tomorrow's program
 */

export function useGetTomorrowProgram<TData = Awaited<ReturnType<typeof getTomorrowProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTomorrowProgram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTomorrowProgramQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retrieve today's program schedule
 * @summary Get today's program
 */
export type getTodayProgramResponse200 = {
  data: ProgramResponse[]
  status: 200
}
    
export type getTodayProgramResponseSuccess = (getTodayProgramResponse200) & {
  headers: Headers;
};
;

export type getTodayProgramResponse = (getTodayProgramResponseSuccess)

export const getGetTodayProgramUrl = () => {


  

  return `/program/today`
}

export const getTodayProgram = async ( options?: RequestInit): Promise<getTodayProgramResponse> => {
  
  return customInstance<getTodayProgramResponse>(getGetTodayProgramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTodayProgramQueryKey = () => {
    return [
    `/program/today`
    ] as const;
    }

    
export const getGetTodayProgramQueryOptions = <TData = Awaited<ReturnType<typeof getTodayProgram>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTodayProgramQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTodayProgram>>> = ({ signal }) => getTodayProgram({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTodayProgramQueryResult = NonNullable<Awaited<ReturnType<typeof getTodayProgram>>>
export type GetTodayProgramQueryError = unknown


export function useGetTodayProgram<TData = Awaited<ReturnType<typeof getTodayProgram>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodayProgram>>,
          TError,
          Awaited<ReturnType<typeof getTodayProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodayProgram<TData = Awaited<ReturnType<typeof getTodayProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTodayProgram>>,
          TError,
          Awaited<ReturnType<typeof getTodayProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTodayProgram<TData = Awaited<ReturnType<typeof getTodayProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get today's program
 */

export function useGetTodayProgram<TData = Awaited<ReturnType<typeof getTodayProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTodayProgram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTodayProgramQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




/**
 * Retrieve the currently running program
 * @summary Get current program
 */
export type getCurrentProgramResponse200 = {
  data: ProgramResponse[]
  status: 200
}
    
export type getCurrentProgramResponseSuccess = (getCurrentProgramResponse200) & {
  headers: Headers;
};
;

export type getCurrentProgramResponse = (getCurrentProgramResponseSuccess)

export const getGetCurrentProgramUrl = () => {


  

  return `/program/current`
}

export const getCurrentProgram = async ( options?: RequestInit): Promise<getCurrentProgramResponse> => {
  
  return customInstance<getCurrentProgramResponse>(getGetCurrentProgramUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetCurrentProgramQueryKey = () => {
    return [
    `/program/current`
    ] as const;
    }

    
export const getGetCurrentProgramQueryOptions = <TData = Awaited<ReturnType<typeof getCurrentProgram>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCurrentProgramQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCurrentProgram>>> = ({ signal }) => getCurrentProgram({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCurrentProgramQueryResult = NonNullable<Awaited<ReturnType<typeof getCurrentProgram>>>
export type GetCurrentProgramQueryError = unknown


export function useGetCurrentProgram<TData = Awaited<ReturnType<typeof getCurrentProgram>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentProgram>>,
          TError,
          Awaited<ReturnType<typeof getCurrentProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentProgram<TData = Awaited<ReturnType<typeof getCurrentProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCurrentProgram>>,
          TError,
          Awaited<ReturnType<typeof getCurrentProgram>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCurrentProgram<TData = Awaited<ReturnType<typeof getCurrentProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get current program
 */

export function useGetCurrentProgram<TData = Awaited<ReturnType<typeof getCurrentProgram>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCurrentProgram>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCurrentProgramQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




