/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  SeatResponse,
  TheaterResponse
} from '../../models';

import { customInstance } from '../../mutator';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getTheaterSeatsResponse200 = {
  data: SeatResponse[]
  status: 200
}
    
export type getTheaterSeatsResponseSuccess = (getTheaterSeatsResponse200) & {
  headers: Headers;
};
;

export type getTheaterSeatsResponse = (getTheaterSeatsResponseSuccess)

export const getGetTheaterSeatsUrl = (id: string,) => {


  

  return `/theater/${id}/seats`
}

export const getTheaterSeats = async (id: string, options?: RequestInit): Promise<getTheaterSeatsResponse> => {
  
  return customInstance<getTheaterSeatsResponse>(getGetTheaterSeatsUrl(id),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getGetTheaterSeatsQueryKey = (id: string,) => {
    return [
    `/theater/${id}/seats`
    ] as const;
    }

    
export const getGetTheaterSeatsQueryOptions = <TData = Awaited<ReturnType<typeof getTheaterSeats>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTheaterSeatsQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTheaterSeats>>> = ({ signal }) => getTheaterSeats(id, { signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTheaterSeatsQueryResult = NonNullable<Awaited<ReturnType<typeof getTheaterSeats>>>
export type GetTheaterSeatsQueryError = unknown


export function useGetTheaterSeats<TData = Awaited<ReturnType<typeof getTheaterSeats>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheaterSeats>>,
          TError,
          Awaited<ReturnType<typeof getTheaterSeats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheaterSeats<TData = Awaited<ReturnType<typeof getTheaterSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTheaterSeats>>,
          TError,
          Awaited<ReturnType<typeof getTheaterSeats>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTheaterSeats<TData = Awaited<ReturnType<typeof getTheaterSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTheaterSeats<TData = Awaited<ReturnType<typeof getTheaterSeats>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTheaterSeats>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTheaterSeatsQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




export type listTheatersResponse200 = {
  data: TheaterResponse[]
  status: 200
}
    
export type listTheatersResponseSuccess = (listTheatersResponse200) & {
  headers: Headers;
};
;

export type listTheatersResponse = (listTheatersResponseSuccess)

export const getListTheatersUrl = () => {


  

  return `/theater/list`
}

export const listTheaters = async ( options?: RequestInit): Promise<listTheatersResponse> => {
  
  return customInstance<listTheatersResponse>(getListTheatersUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getListTheatersQueryKey = () => {
    return [
    `/theater/list`
    ] as const;
    }

    
export const getListTheatersQueryOptions = <TData = Awaited<ReturnType<typeof listTheaters>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTheatersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTheaters>>> = ({ signal }) => listTheaters({ signal, ...requestOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTheatersQueryResult = NonNullable<Awaited<ReturnType<typeof listTheaters>>>
export type ListTheatersQueryError = unknown


export function useListTheaters<TData = Awaited<ReturnType<typeof listTheaters>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTheaters>>,
          TError,
          Awaited<ReturnType<typeof listTheaters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTheaters<TData = Awaited<ReturnType<typeof listTheaters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTheaters>>,
          TError,
          Awaited<ReturnType<typeof listTheaters>>
        > , 'initialData'
      >, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTheaters<TData = Awaited<ReturnType<typeof listTheaters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListTheaters<TData = Awaited<ReturnType<typeof listTheaters>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTheaters>>, TError, TData>>, request?: SecondParameter<typeof customInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTheatersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




