/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Movie Reservation System API
 * API documentation for the Movie Reservation System
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ShowCreateRequest,
  ShowIdRequest,
  ShowResponse
} from '../../models';

import { customInstance } from '../../mutator';




export type findShowByIdResponse200 = {
  data: ShowResponse
  status: 200
}
    
export type findShowByIdResponseSuccess = (findShowByIdResponse200) & {
  headers: Headers;
};
;

export type findShowByIdResponse = (findShowByIdResponseSuccess)

export const getFindShowByIdUrl = () => {


  

  return `/show/find`
}

export const findShowById = async (showIdRequest: ShowIdRequest, options?: RequestInit): Promise<findShowByIdResponse> => {
  
  return customInstance<findShowByIdResponse>(getFindShowByIdUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      showIdRequest,)
  }
);}




export const getFindShowByIdMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof findShowById>>, TError,{data: ShowIdRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof findShowById>>, TError,{data: ShowIdRequest}, TContext> => {

const mutationKey = ['findShowById'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof findShowById>>, {data: ShowIdRequest}> = (props) => {
          const {data} = props ?? {};

          return  findShowById(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FindShowByIdMutationResult = NonNullable<Awaited<ReturnType<typeof findShowById>>>
    export type FindShowByIdMutationBody = ShowIdRequest
    export type FindShowByIdMutationError = unknown

    export const useFindShowById = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof findShowById>>, TError,{data: ShowIdRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof findShowById>>,
        TError,
        {data: ShowIdRequest},
        TContext
      > => {
      return useMutation(getFindShowByIdMutationOptions(options), queryClient);
    }
    export type createShowResponse200 = {
  data: string
  status: 200
}
    
export type createShowResponseSuccess = (createShowResponse200) & {
  headers: Headers;
};
;

export type createShowResponse = (createShowResponseSuccess)

export const getCreateShowUrl = () => {


  

  return `/show/create`
}

export const createShow = async (showCreateRequest: ShowCreateRequest, options?: RequestInit): Promise<createShowResponse> => {
  
  return customInstance<createShowResponse>(getCreateShowUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      showCreateRequest,)
  }
);}




export const getCreateShowMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShow>>, TError,{data: ShowCreateRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createShow>>, TError,{data: ShowCreateRequest}, TContext> => {

const mutationKey = ['createShow'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createShow>>, {data: ShowCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createShow(data,)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateShowMutationResult = NonNullable<Awaited<ReturnType<typeof createShow>>>
    export type CreateShowMutationBody = ShowCreateRequest
    export type CreateShowMutationError = unknown

    export const useCreateShow = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createShow>>, TError,{data: ShowCreateRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createShow>>,
        TError,
        {data: ShowCreateRequest},
        TContext
      > => {
      return useMutation(getCreateShowMutationOptions(options), queryClient);
    }
    export type findAllShowsResponse200 = {
  data: ShowResponse[]
  status: 200
}
    
export type findAllShowsResponseSuccess = (findAllShowsResponse200) & {
  headers: Headers;
};
;

export type findAllShowsResponse = (findAllShowsResponseSuccess)

export const getFindAllShowsUrl = () => {


  

  return `/show/findAll`
}

export const findAllShows = async ( options?: RequestInit): Promise<findAllShowsResponse> => {
  
  return customInstance<findAllShowsResponse>(getFindAllShowsUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}





export const getFindAllShowsQueryKey = () => {
    return [
    `/show/findAll`
    ] as const;
    }

    
export const getFindAllShowsQueryOptions = <TData = Awaited<ReturnType<typeof findAllShows>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFindAllShowsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof findAllShows>>> = ({ signal }) => findAllShows({ signal });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FindAllShowsQueryResult = NonNullable<Awaited<ReturnType<typeof findAllShows>>>
export type FindAllShowsQueryError = unknown


export function useFindAllShows<TData = Awaited<ReturnType<typeof findAllShows>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllShows>>,
          TError,
          Awaited<ReturnType<typeof findAllShows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllShows<TData = Awaited<ReturnType<typeof findAllShows>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof findAllShows>>,
          TError,
          Awaited<ReturnType<typeof findAllShows>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFindAllShows<TData = Awaited<ReturnType<typeof findAllShows>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFindAllShows<TData = Awaited<ReturnType<typeof findAllShows>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof findAllShows>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFindAllShowsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}




